name: "spack updater action"
description: "Given a local spack repository, compare a package to upstream spack and pull request appropriately."
inputs:
  package:
    description: package in local repo to check
    required: true
  user:
    default: username to open PR
    required: true
  token:
    default: token authenticate to GitHub to PR
    required: true
  pull_request:
    description: given changes, attempt to do a pull request
    default: false
  branch:
    description: upstream branch to open issue to request update (defaults to develop)
    default: ""
  local_branch:
    description: branch here to open pull request against (defaults to main)
    default: "main"
  upstream:
    description: upstream to open issue to request update (defaults to spack)
    default: ""
  repo:
    description: local repository with recipes (defaults to PWD)
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Build Package
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        repo: ${{ inputs.repo }}
        branch: ${{ inputs.branch }}
        upstream: ${{ inputs.upstream }}
        package: ${{ inputs.package }}
        pull_request: ${{ inputs.pull_request }}
      run: |
          cmd="python update_package.py --repo ${repo} ${package}"
          if [[ "${upstream}" != "" ]]; then
              cmd="${cmd} --upstream ${upstream}"
          fi
          if [[ "${branch}" != "" ]]; then
              cmd="${cmd} --branch ${branch}"
          fi
          if [[ "${pull_request}" == "true" ]]; then
              cmd="${cmd} --pull_request"
          fi
          echo ${cmd}
          $cmd
      shell: bash

    - name: Pull request changes
      if: ${{ env.spack_updater_changes == 'true' }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        BRANCH_AGAINST: ${{ inputs.local_branch }}
        package: ${{ inputs.package }}
        repo: ${{ inputs.repo }}
      shell: bash
      run: |
          printf "GitHub Actor: ${GITHUB_ACTOR}\n"
          export BRANCH_FROM="update-package/${package}-$(date '+%Y-%m-%d')"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git branch
          git checkout -b "${BRANCH_FROM}" || git checkout "${BRANCH_FROM}"
          git branch
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          repo_path=$(realpath "${repo}")
          tree ${repo_path}
          repo_path=${repo_path}/packages/${package}
          git add $repo_path/*
          if git diff-index --quiet HEAD --; then
              printf "No changes\n"
          else
              printf "Changes\n"
              git commit -m "Automated deployment to update package ${package} $(date '+%Y-%m-%d')"
              git push origin "${BRANCH_FROM}"
              echo "open_pr=1" >> $GITHUB_ENV
          fi
          echo "PULL_REQUEST_FROM_BRANCH=${BRANCH_FROM}" >> $GITHUB_ENV
