name: "spack updater action release check"
description: "Check for updated releases"
inputs:
  token:
    description: GitHub token
    required: true
  package:
    description: name of package in packages folder
    required: true
  repo:
    description: repository with package releases
    required: true
  dry_run:
    description: don't update the file (dry run only)
    required: false
    default: false

outputs:
  version:
    description: "New version"
    value: ${{ steps.check.outputs.version }}
  package:
    description: "Package with version (to install or test build)"
    value: ${{ steps.check.outputs.package }}
  digest:
    description: "Digest of new release"
    value: ${{ steps.check.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Check for New Releases
      id: check
      env:
        package: ${{ inputs.package }}
        repo: ${{ inputs.repo }}
        dry_run: ${{ inputs.dry_run }}
        GITHUB_TOKEN: ${{ inputs.token }}
        action_path: ${{ github.action_path }}
      run: |
        if [ "${dry_run}" == "true" ]; then
            python ${action_path}/scripts/get_releases.py --repo ${repo} packages/${package} --dry-run
        else
            python ${action_path}/scripts/get_releases.py --repo ${repo} packages/${package}
        fi
      shell: bash
