name: "spack updater action issue parser"
description: "Parse an issue into metadata needed for the update"
inputs:
  title:
    description: Issue event title
    required: true
  number:
    description: issue event number
    required: true
  body:
    description: issue body
    required: true

runs:
  using: "composite"
  steps:
    - name: Parse Issue
      env:
        title: ${{ inputs.title }}
        number: ${{ inputs.number }}
        body: ${{ inputs.body }}
        action_path: ${{ github.action_path }}
      run: |
        printf "Issue title: ${title}\n"
        printf "Issue number: ${number}\n"
        echo "${body}" > new-issue.txt
        cat new-issue.txt
        python ${action_path}/scripts/parse_issue.py new-issue.txt
        echo "issue_number=${number}" >> $GITHUB_ENV
        echo "issue_file=${PWD}/new-issue.txt" >> $GITHUB_ENV
      shell: bash
