name: "spack updater upstream updater"
description: "Ensure your develop branch is in sync with spack upstream"
inputs:
  token:
    description: GitHub token
    required: true
  branch:
    description: branch of upstream spack to sync with (defaults to develop).
    required: true
    default: develop
  local_branch:
    description: local branch to sync with upstream (defaults to develop).
    required: true
    default: develop
  push:
    description: Push updates to local branch
    required: false
    default: true
  allow_fail:
    description: Allow pull of upstream branch to fail (defaults to false)
    required: false
    default: false
  repository:
    description: Repository to check out (defaults to local repository)
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      if: ${{ inputs.repository == '' }}
      with:
        ref: ${{ inputs.local_branch }}

    - name: Checkout Repository
      uses: actions/checkout@v3
      if: ${{ inputs.repository != '' }}
      with:
        repository: ${{ inputs.repository }} 
        ref: ${{ inputs.local_branch }}
    - name: Update Spack Upstream
      env:
        allow_fail: ${{ inputs.allow_fail }}
        push: ${{ inputs.push }}
        local_branch: ${{ inputs.local_branch }}
        branch: ${{ inputs.branch }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
          printf "GitHub Actor: ${GITHUB_ACTOR}\n"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"         
          git remote add upstream "https://x-access-token:${GITHUB_TOKEN}@github.com/spack/spack.git"         
          git branch
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git pull upstream ${branch} || git pull upstream ${branch} --ff-only || (
            if [ "${allow_fail}" == "true" ]; then
                printf "Error pulling upstream, but allow_fail is true\n"           
            else
                printf "Error pulling upstream\n"
                exit 1
            fi             
          )
          if [ "${push}" == "true" ]; then
              printf "Pushing updates to ${local_branch}\n"
              git push origin ${local_branch}
          else:
              printf "Not pushing updates to ${local_branch}\n"
              git status
          fi
      shell: bash
