name: Test Actions
on:
  pull_request: []

jobs:
  update-spack:
    name: Check for updates from upstream spack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update with Upstream
        uses: ./upstream
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: researchapps/spack
          push: false

  test-build:
    name: Test Package Builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Look for rust updates
        uses: ./release-check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: rust
          repo: rust-lang/rust

      - name: Test Build
        uses: ./build
        with:
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          package: zlib

#  test-action:
#    name: Test Action Update To Spack
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#      - name: Test Parse Issue
#        run: |
#          pip install -r requirements.txt
#          python parse-issue/scripts/parse_issue.py new-issue.txt

#      - name: Spack Update
#        uses: ./
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          user: ${{ github.actor }}
#          repo: .
#          package: zlib
#          upstream: https://github.com/researchapps/spack
          
#  test-action-from-spack:
#    name: Test New Package From Spack
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3

#      - name: Test Adding New Package
#        uses: ./
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          user: ${{ github.actor }}
#          repo: .
#          package: m4
#          upstream: https://github.com/researchapps/spack
