name: Test Action
on:
  pull_request: []
  push:
    branches:
      main

jobs:
  test-action-from-spack:
    name: Test New Package From Spack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Test Adding New Package
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.actor }}
          repo: .
          package: m4
          upstream: https://github.com/researchapps/spack
          branch: develop
          pull_request: true

      - name: Open Pull Request
        if: ${{ env.open_pr != '' }}
        uses: vsoch/pull-request-action@1.0.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "main"

  test-action:
    name: Test Action Update To Spack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Test Parse Issue
        run: |
          pip install -r requirements.txt
          python parse_issue.py new-issue.txt

      - name: Spack Update
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.actor }}
          repo: .
          package: zlib
          upstream: https://github.com/researchapps/spack
          branch: develop
          pull_request: true
