name: Test Actions
on:
  pull_request: []

jobs:
  update-spack:
    name: Check for updates from upstream spack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update with Upstream
        uses: ./upstream
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: researchapps/spack
          push: false
          allow_fail: true

        # hack to ensure action can complete
      - name: Checkout Repository
        uses: actions/checkout@v4

  test-release-check:
    name: Test Release Checker
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        package: [[alan, mpdunne/alan],
                  [openslide, ""]]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Look for ${{ matrix.package[0] }} updates
        uses: ./release-check
        id: check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ matrix.package[0] }}
          repo: ${{ matrix.package[1] }}
          pull_request: false

      - name: Check Output
        env:
         version: ${{ steps.check.outputs.version }}
         package: ${{ steps.check.outputs.package }}
         digest: ${{ steps.check.outputs.digest }}
        run: |
          echo ${package}
          echo ${version}
          echo ${digest}
          cat packages/${{ matrix.package[0] }}/package.py

  test-build:
    name: Test Package Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Test Build
        uses: ./build
        with:
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          package: alan

  test-action:
    name: Test Action Update To Spack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Test Parse Issue
        run: |
          pip install -r requirements.txt
          python parse-issue/scripts/parse_issue.py new-issue.txt

      - name: Spack Update
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.actor }}
          repo: .
          package: alan
          upstream: https://github.com/researchapps/spack
          local_branch: main
