name: Test Action
on:
  pull_request: []
  push:
    branches:
      main

jobs:
  test-action:
    name: Test Action Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Spack Update
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: .
          package: zlib
          upstream: https://github.com/vsoch/spack
          branch: develop
          pull_request: true
